### ISSUE TITLE
real-scanned datasets

### ISSUE THREAD

**Issue by BingHan0458** [yunhe20/Grad-PU#5]
Dear Author, thank you for the nice work. I really want to test these real datasets including ScanObjectNN and KITTI in your paper using my own method. If possible, could you send me a copy of the original data? Thank you very much. My email is bhan0458@bjtu.edu.cn. Thank you again.

**Comment by yunhe20** [comment]
We directly download the [ScanObjectNN](https://hkust-vgd.github.io/scanobjectnn/) and [KITTI](https://www.cvlibs.net/datasets/kitti/) datasets from the official project pages. Please check the links.
