### ISSUE TITLE
comparison with NeuralPoints

### ISSUE THREAD

**Issue by lisj575** [yunhe20/Grad-PU#6]
Hi, thank you for your excellent work. I notice that you make a comparison with [NeuralPoints](https://github.com/WanquanF/NeuralPoints) on PU-GAN dataset, but they need normals as supervision which is unavailable in the dataset. So how did you test their method?

**Comment by yunhe20** [comment]
You can estimate the normals, and then use the estimated results for supervision.

**Comment by lisj575** [comment]
Thanks for your reply. Have you modified their code to test it on the PU-GAN dataset with their pre-trained model? I have been unable to reproduce their results, even when dividing the point cloud into patches. The quantitative results I obtained are close to that of PU-GAN.

**Comment by kangya998** [comment]
> You can estimate the normals, and then use the estimated results for supervision.

Hi,Congratulations on the groundbreaking progress in your work! Can you share the details of training Neps

**Comment by yunhe20** [comment]
Please directly ask the authors of NeuralPoints for help if you meet any problem during the model training or testing.
