### ISSUE TITLE
CD about the results of surface reconstruction

### ISSUE THREAD

**Issue by BingHan0458** [yunhe20/Grad-PU#8]
Dear Author, thank you for the nice work. I also want to know that in section 4.3(Impact on Downstream Tasks), how to evaluate the CD about the results of surface reconstruction?
![ff3354aa2b2aa5447701bbf3d5499ac](https://github.com/yunhe20/Grad-PU/assets/74912676/338fa018-96ad-496f-b9ae-a50a972ea4a5)
I think the steps are said like PUGeo-Net in section 4.1(Experiment Settings): "We densely sampled 200,000 points from reconstructed surface. CD, HD and JSD between the densely sampled points from reconstructed surface and the groundtruth mesh were finally computed for measuring the surface reconstruction quality. Such new measurements are denoted as CD#, HD# and JSD#."
Is it like this? Or how to calculate it in your paper?

**Comment by yunhe20** [comment]
Yes. We uniformly sample 500k points from the reconstructed surfaces and ground-truth surfaces to calculate the CD metric.

**Comment by BingHan0458** [comment]
Okay, thank you for your reply!
