### ISSUE TITLE
A question about "Chamfer_3D" and "pointops"

### ISSUE THREAD

**Issue by QWTforGithub** [yunhe20/Grad-PU#9]
Thank you for your code. When I complier the "Chamfer_3D" and "pointops", there is a question:

python setup.py install
_running install
/home/test/anaconda3/envs/pu/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/test/anaconda3/envs/pu/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing chamfer_3D.egg-info/PKG-INFO
writing dependency_links to chamfer_3D.egg-info/dependency_links.txt
writing top-level names to chamfer_3D.egg-info/top_level.txt
reading manifest file 'chamfer_3D.egg-info/SOURCES.txt'
writing manifest file 'chamfer_3D.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'chamfer_3D' extension
Emitting ninja build file /media/data/abiao/qcode/Grad-PU-main/models/Chamfer3D/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.1.git.kitware.jobserver-1
g++ -pthread -shared -B /home/test/anaconda3/envs/pu/compiler_compat -L/home/test/anaconda3/envs/pu/lib -Wl,-rpath=/home/test/anaconda3/envs/pu/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/data/abiao/qcode/Grad-PU-main/models/Chamfer3D/build/temp.linux-x86_64-cpython-37/chamfer3D.o /media/data/abiao/qcode/Grad-PU-main/models/Chamfer3D/build/temp.linux-x86_64-cpython-37/chamfer_cuda.o -L/home/test/anaconda3/envs/pu/lib/python3.7/site-packages/torch/lib -L/home/test/cudnn/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-37/chamfer_3D.cpython-37m-x86_64-linux-gnu.so
**g++: error: /media/data/abiao/qcode/Grad-PU-main/models/Chamfer3D/build/temp.linux-x86_64-cpython-37/chamfer3D.o: No such file or directory
g++: error: /media/data/abiao/qcode/Grad-PU-main/models/Chamfer3D/build/temp.linux-x86_64-cpython-37/chamfer_cuda.o: No such file or directory**
error: command '/usr/local/bin/g++' failed with exit code 1_
I use g++ 7.5, please give some suggestions, thank you!

**Comment by yunhe20** [comment]
I have not encountered this issue before. Did you use the ubuntu system to complie the libraries? I suggest you open an issue in the [ChamferDistancePytorch](https://github.com/ThibaultGROUEIX/ChamferDistancePytorch) and [PAConv](https://github.com/CVMI-Lab/PAConv) reponsitories, since the two libraries are originally borrowed from them.

**Comment by QWTforGithub** [comment]
> I have not encountered this issue before. Did you use the ubuntu system to complie the libraries? I suggest you open an issue in the [ChamferDistancePytorch](https://github.com/ThibaultGROUEIX/ChamferDistancePytorch) and [PAConv](https://github.com/CVMI-Lab/PAConv) reponsitories, since the two libraries are originally borrowed from them.

Thank you for your reply. I set LIBRARY_PATH and LD_LIBRARY_PATH to fix this problem.
